-- ============================================================
-- Migration: Per-cohort achievements
-- Run ONCE in the Supabase SQL editor, top to bottom.
--
-- Turns the shared achievement catalog into independent per-cohort catalogs.
--   * achievements gains cohort_id (each row belongs to one cohort) and
--     is_unlocked moves back onto the row (per-cohort unlock state).
--   * Existing rows are kept by "test-cohort" (the keeper / template).
--   * Every OTHER existing cohort gets its own full copy of the catalog,
--     carrying its own unlock state, and its submissions are re-pointed to
--     its copies (matched by slug) so no progress is lost.
--   * cohort_achievement_unlocks is dropped (redundant now).
--   * slug uniqueness becomes (cohort_id, slug).
--
-- IMPORTANT: deploy the matching app code together with this migration.
-- ============================================================

-- 1. Drop the global slug-unique FIRST so the per-cohort copies (which reuse
--    the same slugs) don't collide while we build them. Name-agnostic.
do $$
declare cname text;
begin
  select conname into cname
  from pg_constraint
  where conrelid = 'achievements'::regclass
    and contype = 'u'
    and pg_get_constraintdef(oid) ilike '%(slug)%';
  if cname is not null then
    execute format('alter table achievements drop constraint %I', cname);
  end if;
end $$;

-- 2. New columns (cohort_id nullable for now so we can backfill).
alter table achievements add column cohort_id uuid references cohorts(id) on delete cascade;
alter table achievements add column is_unlocked boolean not null default false;

-- 3. Backfill + per-cohort copies.
do $$
declare
  v_keeper uuid;
begin
  select id into v_keeper from cohorts where join_code = 'TEST-COHORT' limit 1;
  if v_keeper is null then
    raise exception 'Keeper cohort (TEST-COHORT) not found.';
  end if;

  -- 3a. The existing rows belong to the keeper.
  update achievements set cohort_id = v_keeper where cohort_id is null;

  -- 3b. Carry the keeper's unlock state onto its rows.
  update achievements a
  set is_unlocked = coalesce(u.is_unlocked, false)
  from cohort_achievement_unlocks u
  where u.achievement_id = a.id and u.cohort_id = v_keeper;

  -- 3c. Copy the whole catalog for every other cohort, carrying ITS unlock
  --     state. New ids are generated by the default.
  insert into achievements
    (cohort_id, slug, session_number, block_number, title, description, xp,
     proof_type, proof_config, is_secret, is_active, sort_order, is_unlocked)
  select c.id, a.slug, a.session_number, a.block_number, a.title, a.description, a.xp,
         a.proof_type, a.proof_config, a.is_secret, a.is_active, a.sort_order,
         coalesce(u.is_unlocked, false)
  from achievements a
  cross join cohorts c
  left join cohort_achievement_unlocks u
    on u.cohort_id = c.id and u.achievement_id = a.id
  where a.cohort_id = v_keeper and c.id <> v_keeper;

  -- 3d. Re-point each non-keeper cohort's submissions to its own copies,
  --     matched by slug. (Comma-joins + WHERE: Postgres forbids referencing the
  --     UPDATE target `s` inside an explicit JOIN in the FROM clause.)
  update submissions s
  set achievement_id = newa.id
  from achievements olda, teams t, achievements newa
  where s.achievement_id = olda.id
    and t.id = s.team_id
    and newa.cohort_id = t.cohort_id
    and newa.slug = olda.slug
    and olda.cohort_id = v_keeper
    and t.cohort_id <> v_keeper;
end $$;

-- 4. Lock it down.
alter table achievements alter column cohort_id set not null;
alter table achievements add constraint achievements_cohort_slug_key unique (cohort_id, slug);

-- 5. Drop the now-redundant unlock table.
drop table cohort_achievement_unlocks;
